queue_rules:
  - name: main
    allow_inplace_checks: True
    allow_checks_interruption: True
    speculative_checks: 1
    batch_size: 2
    # Wait for a few minutes to embark 2 tickets together in a merge train
    batch_max_wait_time: "3 minutes"
    conditions:
      # Mergify automatically applies status check, approval, and conversation rules,
      # which are the same as the GitHub main branch protection rules
      # https://docs.mergify.com/conditions/#about-branch-protection
      - base=main

pull_request_rules:
  - name: main queue triggered when CI passes with 1 review
    conditions:
      # This queue handles a PR if:
      # - it targets main
      # - is not in draft
      #   including automated dependabot PRs.
      - base=main
      - -draft
      - label!=do-not-merge
    actions:
      queue:
        name: main
        method: squash